all: demo11 demo12 11 12


demo11: demo11.cpp 
	g++ -o demo11 demo11.cpp 


demo12: demo12.cpp 
	g++ -o demo12 demo12.cpp 

11:11.cpp
	g++ -o 11 11.cpp 

12:12.cpp
	g++ -o 12 12.cpp 

clean:
	rm -f 11 12 demo11 demo12